### ISSUE TITLE
Todo Item Mockup: View of a collapsed Todo item

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#13]
For this ticket, we need to have a visual of:
- Title
- description
- Due date
- Priority

Edge cases:
- If the title is too long, shorten it
- If the Description is too long, shorten it
- If no description, due date, or priority exists, omit

See parent ticket for more details #2 .

**Comment by klooopmoo** [comment]
https://www.figma.com/file/3qwAJgEMySCRAOq4ZygXZb/TODO?node-id=0%3A1

Added how a todo item should look like at a glance. 

I added a navbar and side bar as placeholders to have an idea of how and where the todo items will be listed.
