### ISSUE TITLE
Investigate which frontend framework to use

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#17]
Investigate the following options as a frontend framework/tech stack:
- Flutter: https://docs.flutter.dev/codelabs
- React(Native): https://reactjs.org/tutorial/tutorial.html
- JS/HTML/CSS: 
  - https://developer.mozilla.org/en-US/docs/Learn/JavaScript
  - https://developer.mozilla.org/en-US/docs/Learn/HTML
  - https://developer.mozilla.org/en-US/docs/Learn/CSS

We have broken this ticket out:
- #20 
- #19 
- #21 
- #22

**Comment by klooopmoo** [comment]
JS/HTML/CSS : https://github.com/klooopmoo/snippets/tree/main/VanillaJS
React:https://github.com/klooopmoo/CounterApp/tree/main/VanillaJS

As of now, React seems more intuitive than VanillaJS.  I still need to test out flutter. 
Need further review if I would like to use this for the front end. I request a new ticket to test out API calls from the backend to the front end.

**Comment by klooopmoo** [comment]
After review, I decided to use Flutter over Vanilla JS and React. The higher level of abstraction makes it easier to develop and to learn.
