### ISSUE TITLE
Create a Counter App in Flutter

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#19]
This is a ticket to learn more about how to work with flutter as part of https://github.com/SAKA-club/todo/issues/17

Feel free to spend some time looking at https://docs.flutter.dev/codelabs

For the Counter App UI:
- [x] Include a display of the current counter
- [x] Provide the ability to increment, decrement, and reset the count
- [x] (Optional) Include a random image
- [x] (Optional) Include the ability to change the random image without navigating away from the page

API calls that will need to be made to support this UI:
- [x] GET request to get the current count from the backend. This should be done when the page loads so the counter is initially set to the correct amount.
- [x] PUT request to update the count. This should be done every time the count is adjusted
- [ ] (Optional) GET request to get a new random image.

Use the backend developed in this ticket to store the state of the counter: https://github.com/SAKA-club/todo/issues/20

**Comment by klooopmoo** [comment]
closes #19

Please see the attached [link](https://github.com/klooopmoo/CounterAppFlutterGo)
