### ISSUE TITLE
Create a Counter App backend to store the count state

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#20]
This backend can be used to power each of the frontends developed for #17 

Create the following endpoints:
- [x] GET `/` Should return the work down for a given frontend (return the index.html)
- [x] GET `/state` Should return a json format of state. The state object should have a property with the name `count` and an integer value
- [x] PUT `/state` Should take a json format of state as specified above and return that same object back to the caller.

**Comment by klooopmoo** [comment]
Please see the attached [repo](https://github.com/klooopmoo/CounterApp/blob/main/VanillaJS/main.go) for this issue 
closes #20

**Comment by spencerreeves** [comment]
Looks good, close out ticket when ready.
