### ISSUE TITLE
Create a Counter App in VanillaJS

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#21]
This is a ticket to learn more about how to work with flutter as part of https://github.com/SAKA-club/todo/issues/17

For the Counter App UI:
- [x] Include a display of the current counter
- [x] Provide the ability to increment, decrement, and reset the count
- [x] (Optional) Include a random image
- [ ] (Optional) Include the ability to change the random image without navigating away from the page

API calls that will need to be made to support this UI:
- [x] GET request to get the current count from the backend. This should be done when the page loads so the counter is initially set to the correct amount.
- [x] PUT request to update the count. This should be done every time the count is adjusted
- [ ] (Optional) GET request to get a new random image.

Use the backend developed in this ticket to store the state of the counter: https://github.com/SAKA-club/todo/issues/20

**Comment by klooopmoo** [comment]
for this we do not have to keep the state once i increment the value on my UI correct?

For example,  I am able to put the value of 10 using Insomnia. Once I refresh, my UI should show 10 but if increase the value in my UI to 12 and hit refresh the value should go back to 10. Is that correct?

**Comment by spencerreeves** [comment]
The state should be preserved anytime you make a modification. In the situation outlined above, the state is not preserved, and therefore is incorrect behavior. If you increment the counter and refresh the counter should persist the count - e.g. increment to 2, refresh, count should be 2.

**Comment by klooopmoo** [comment]
Please see the attached [repo](https://github.com/klooopmoo/CounterApp/blob/main/VanillaJS/public/index.html)

closes #21
