### ISSUE TITLE
Create a Counter App in React

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#22]
This is a ticket to learn more about how to work with flutter as part of https://github.com/SAKA-club/todo/issues/17

See how to make API call here: https://rapidapi.com/blog/how-to-use-an-api-with-react/

For the Counter App UI:
- [x] Include a display of the current counter
- [x] Provide the ability to increment, decrement, and reset the count
- [ ] (Optional) Include a random image
- [ ] (Optional) Include the ability to change the random image without navigating away from the page

API calls that will need to be made to support this UI:
- [ ] GET request to get the current count from the backend. This should be done when the page loads so the counter is initially set to the correct amount.
- [ ] PUT request to update the count. This should be done every time the count is adjusted
- [ ] (Optional) GET request to get a new random image.

Use the backend developed in this ticket to store the state of the counter: https://github.com/SAKA-club/todo/issues/20

**Comment by klooopmoo** [comment]
Please see attached [link](https://github.com/klooopmoo/CounterApp)

I was able to keep state but unable to show the counter on react. I've decided to go with Flutter.
