### ISSUE TITLE
Init Project: Setup app for deployment

### ISSUE THREAD

**Issue by spencerreeves** [SAKA-club/todo#9]
To make our code accessible to the public, we need to deploy. It is better to iron our the kinks of deployment and hosting early on in case we need to make any implementation changes. 

- [x] Investigate deployment options. Things to factor in ease of deployment, cost, vendor-lockin. Think about how easy it is to deploy a web server (backend) and connect to a database. We will use a [CDN](https://www.cloudflare.com/learning/cdn/what-is-a-cdn/) provider to host files (front end).
    - We will  be using [fly.io](https://fly.io/docs/getting-started/golang/) to deploy our backend and database.
- [x] Write steps to deploy web server in README
- [x] Create any useful commands in Makefile to make deployment easier.

See Parent ticket (https://github.com/SAKA-club/todo/issues/6 ) for more details about Init Project.

**Comment by klooopmoo** [comment]
fly.io creates a fly.toml file after successfully deploying. Is that something that needs to be checked in or should be included in .gitignored

**Comment by spencerreeves** [comment]
If it doesn't include sensitive information, then yeah, check it in.
